function out1 = func_f(t,in2)
%FUNC_F
%    OUT1 = FUNC_F(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    08-Mar-2023 10:33:02

x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
out1 = [x3;x4;x1.*-3.6e+1-sin(x2).*(9.81e+2./1.0e+2)+x1.*x4.^2+3.6e+1;x1.*(cos(x2).*9.81e+2+x3.*x4.*2.0e+2).*(-1.0./1.0e+2)];
