function out1 = func_f_2D(t,in2)
%func_f_2D
%    OUT1 = func_f_2D(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Mar-2023 14:50:29

x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
t2 = x1.^2;
t3 = x2.^2;
t4 = t2+t3;
t5 = sqrt(t4);
t6 = 1.0./t5;
out1 = [x3;x4;t6.*x1.*(t5-1.0).*-3.6e+1;t6.*(t5.*4.9e+1-x2.*1.8e+2+t5.*x2.*1.8e+2).*(-1.0./5.0)];
