function out1 = func_J_2D(in1)
%func_J_2D
%    OUT1 = func_J_2D(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Mar-2023 14:50:29

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1.^2;
t3 = x2.^2;
t4 = t2+t3;
t5 = 1.0./t4;
t6 = 1.0./sqrt(t4);
out1 = reshape([t6.*x1,-t5.*x2,t6.*x2,t5.*x1],[2,2]);
