function out1 = func_M_2D(t,in2)
%func_M_2D
%    OUT1 = func_M_2D(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Mar-2023 14:50:29

out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
